name: Merge Queue
on:
  pull_request:
    types: [labeled]

concurrency: merge queue
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Should probably do some validation that the PR can be merged(e.g. is approved)
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: MixmasterFresh/merge-queue-start@ad565f6aab839f588049231ac360ef0cc155382b
        with:
          queue-label: queued
          failed-label: failed
          merged-label: merged

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
